### ISSUE TITLE
Bug: line number  added to commented out latex code block

### ISSUE THREAD

**Issue by danieltomasz** [mayurankv/Obsidian-Code-Styler#122]
thank you for the plug-in, the code in obsidian is much better now!

My problem: I have a commented out latex code

````markdown 

<!--
```{=latex}
\epigraph{\scriptsize\raggedleft \ldots \: it becomes clear that I am not one and simple, but complex and many.}{\scriptsize --- \textup{Virginia Woolf}, The Waves}
```
-->

```` 

when live preview  is enabled and line number in the plugins are active, i see the number 1 before ` \epigraph`;
adding =latex and latex to excluded  in option doesn’t work. Bug was introduced recently, i had code styler enabled and didn’t notice that line numbers appeared here.

### Steps to reproduce

copy the code and enable line number

````markdown

<!--
```{=latex}
\epigraph{\scriptsize\raggedleft \ldots \: it becomes clear that I am not one and simple, but complex and many.}{\scriptsize --- \textup{Virginia Woolf}, The Waves}
```
-->

````

### Expected behaviour

code numbers  shouldnt appears in the commented out code chunks 

### Current behaviour

1 is visible at the beginning of line
### Environment

- Plugin Version: 1.0.10
- Obsidian Version:  1.4.5
- Platform:  Desktop
- OS:  
- Theme: Vanilla
- CSS Snippets:  

### Screenshots

![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/7980381/f78b234b-86fd-4c7d-ba8b-9c7222572ffb)

**Comment by mayurankv** [comment]
Ooh that's definitely unintentional, I'll look into it and try and get it sorted ASAP. Thanks for the report (and the kind words!)

**Comment by mayurankv** [comment]
Quick note, I've checked that adding `{=latex}` to the `ignored language` setting does indeed remove the line numbering but tbh, it shouldn't happen if commented anyway so I do need to do a fix

**Comment by mayurankv** [comment]
Also fyi, you can add `ignore` as a codeblock parameter to specifically ignore a codeblock or `code-styler-ignore: true` to the frontmatter to ignore the whole file.

**Comment by danieltomasz** [comment]
I noticed on more thing:

multiline `%%`  block that contain latex code block (the same as in example but without html comments)doesnt seem to have an effect on it, when in live preview it looks like no comment were applied, it is intended effect or bug?

**Comment by mayurankv** [comment]
This should be fixed now and released with the next release (the HTML comments issue).

**Comment by mayurankv** [comment]
r.e. the multiline `%%` comments, am I incorrect or does that not still occur when the plugin is disabled? I understand the multiline comments to be kind of just excluded from reading view, but markdown inside them is rendered as it normally would be in live preview. If I've misunderstood something please do correct me!

**Comment by mayurankv** [comment]
I'm going to close this for now as completed but if there is anything else or work is needed on the `%%` comments, I'll reopen it. Thanks!
