### ISSUE TITLE
Bug: inline code styling issues

### ISSUE THREAD

**Issue by evfinkn** [mayurankv/Obsidian-Code-Styler#136]
## Describe the bug

In reading mode, the background of inline code extends too far to the right.

### Steps to reproduce

Go into reading mode after adding some inline code followed by text, such as:

````markdown
Arithmetic: `{python} 1 + 1` is an example of addition in Python.
````

### Expected behaviour

The rendered markdown looks more or less the same as in editing mode.

### Current behaviour

The background of the inline code is wider than it should be, reaching far enough to touch the text.

### Environment

- Plugin Version: 1.0.11
- Obsidian Version:  1.4.5
- Platform:  desktop
- OS:  macOS
- Theme:  dark
- CSS Snippets:  none
- Plugin Settings: defaults

### Screenshots

Editing mode:
<img width="440" alt="editing" src="https://github.com/mayurankv/Obsidian-Code-Styler/assets/6924485/cc2bb8b3-4305-4f44-bce4-7534151cd3c4">

Reading mode:
<img width="440" alt="Screenshot 2023-09-11 at 2 57 27 PM" src="https://github.com/mayurankv/Obsidian-Code-Styler/assets/6924485/5da0e237-4ce9-40ae-9f9d-30b7d4c9f3bb">

### Additional context

The issue occurs even if the "Style Inline Code" option is disabled, but is fixed if "Syntax Highlight Inline Code" is disabled or if the plugin is disabled.

**Comment by mayurankv** [comment]
Hi, sorry for the wait, I'm quite busy with work right now. I'll try and look into it as soon as I can (in a couple of weeks). I'll update you then. Thanks for the bug report!

**Comment by mayurankv** [comment]
I'm exploring this issue right now and it onyl occurs when a language is set. I think it may be to do with the tokens used as they are normally in codeblocks where horizontal space isn't needed. i.e. `1 + 1` has the spaces stripped but still appears properly spaced. I think the last character has this right space still included which is causing issues. Quite struggling on how to solve this though.

**Comment by mayurankv** [comment]
Haha, I've fixed it with some unicode hackery. Solved now! Will be included in the next release.

**Comment by mayurankv** [comment]
This might be causing the issue with #263
