### ISSUE TITLE
Bug: highlight line number not working

### ISSUE THREAD

**Issue by hopezh** [mayurankv/Obsidian-Code-Styler#161]
As shown below, turning on "Highlight Line Numbers" doesn't seem to work:

<img width="1833" alt="Screenshot 2023-10-07 at 15 28 50" src="https://github.com/mayurankv/Obsidian-Code-Styler/assets/23435810/a73bb7c3-1728-4d44-9857-429d6bbe6399">

<img width="940" alt="Screenshot 2023-10-07 at 15 29 16" src="https://github.com/mayurankv/Obsidian-Code-Styler/assets/23435810/d349f474-4e7e-486d-b67c-fadea49c8514">

**Comment by mayurankv** [comment]
Sorry from your screenshot, I presume this is in editing mode? Does the issue also occur in reading mode?

Also could you provide the markdown of a codeblock which doesn't work (including the parameters), i.e. how you highlight? This would be as in the bug report template (it would be very helpful for you to fill that out completely!).

Just to clarify, the orange and yellow lines in your second screenshot, are those not highlighted lines?

**Comment by mayurankv** [comment]
Oh sorry, I was being silly in my last (now deleted) message! This is highlight line numbers, sorry. Could you fill out the Bug Report template so I know what theme, version, platform etc. you are on? Also providing a gif where your cursor moves would be really helpful!

I'm a bit busy at the moment but I'll try and look into this soon. Thanks for the bug report!

**Comment by mayurankv** [comment]
Hiya, I have some time to look into this. Was it resolved? If not, what theme are you using? That would be very helpful!

**Comment by mayurankv** [comment]
Ok, after a little bit of testing, I believe this error occurs in all themes in editing mode. Please correct me if I'm wrong.

**Comment by mayurankv** [comment]
This will be fixed in the next release (pretty imminently). Please let me know if that wasn't indeed your issue or this hasn't been solved. Thanks for the report!
