### ISSUE TITLE
Feature Request: Add support for slides

### ISSUE THREAD

**Issue by Mideks** [mayurankv/Obsidian-Code-Styler#164]
Your extention does not work with Slides (Core plugin)
![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/38502324/a3c720d3-9a92-4ecd-a5b5-4360998af377)

**Comment by mayurankv** [comment]
Ah, thanks for highlighting this! Would definitely be amazing to get it to work with slides. I'm quite busy right now, but this is definitely on my roadmap!

**Comment by mayurankv** [comment]
This is now included in the latest release! Closing the issue.
