### ISSUE TITLE
Feature Request: how could I use unwrap code block in edit mode?

### ISSUE THREAD

**Issue by TimFruit** [mayurankv/Obsidian-Code-Styler#176]
![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/23203575/4e0ac353-ab3a-46c0-956a-43c22115e155)

**Comment by mayurankv** [comment]
This is something that's currently in the pipeline: see #12. Unfortunately, it's a surprisingly hard issue and I'm currently a little bit busy. You could subscribe to that issue if you want to be updated on progress with that.

I'm going to close this issue for now as I think its a duplicate but please do correct me if I've misunderstood!
