### ISSUE TITLE
Bug:  unwrap setting doesn't work

### ISSUE THREAD

**Issue by dumitory-dev** [mayurankv/Obsidian-Code-Styler#211]
Hello! Can't configure unwrap code. For some reason this setting doesn't work for me, maybe I need to install some special theme or something?

### Steps to reproduce
Just wrote some long code in codeblock with enabled unwrap setting 

````markdown
```python unwrap:true title:test
skdpaksdopsaopkdpoksapodkpoaskdpokasopkdpoakspodkpaoskdpokaposkdpoakpodkpasokdpoaposdkopaksdpokaspd


klojoioijoijoioijoi
```
````

### Expected behaviour
Unwrap code with horizontal scrolling

### Current behaviour
Default behavior. Code is wrapping 

### Environment

- Plugin Version: 1.1.4
- Obsidian Version: 1.4.16
- Platform:  Desktop 
- OS:  Windows, MacOs
- Theme:  Nord, Default, Solarized 
- CSS Snippets:  no

### Screenshots
<img width="860" alt="image" src="https://github.com/mayurankv/Obsidian-Code-Styler/assets/45358107/548b0b4e-9626-44c1-9330-e79f39822189">
<img width="734" alt="image" src="https://github.com/mayurankv/Obsidian-Code-Styler/assets/45358107/207cb068-326f-4d03-8e94-b68058c534f3">
<img width="1081" alt="image" src="https://github.com/mayurankv/Obsidian-Code-Styler/assets/45358107/bebf4931-f310-4b05-a806-86315aa8fded">

**Comment by mayurankv** [comment]
Sorry just to check is this in edit mode or reading mode? (It appears to be editing mode from the spacing). Unfortunately there are issues with implementing wrapping in edit mode currently. It's something I want to fix but will take some time. See #12. If this is reading mode, let me know and I'll reopen it.
