### ISSUE TITLE
Bug: 渲染错误 render error

### ISSUE THREAD

**Issue by Tback1** [mayurankv/Obsidian-Code-Styler#212]
## Describe the bug
![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/8872546/d6842cff-f777-456a-a691-12dd055c01b5)

### Steps to reproduce

代码如下，可以直接测试:
```
我们来试一试，右键「书签栏」，选择【添加网页】选项，在往常我们会在网址一栏填写书签对应的网址（这就是 `href=""` 中的值），但现在我们在这一栏中填写 JS 代码：`{js icon title:foo} javascript:(function(){alert('你好')})()`

``` javascript
javascript:(function(){alert('你好')})()
```

```
````

### Environment

- Plugin Version: 1.1.4
- Obsidian Version: 1.5.3
- Platform:  Desktop
- OS:  Windows 10 LTSC
- Theme:  < Default or Typora-Vue or Thins3>
- CSS Snippets:  < no >

### Screenshots
**Hope it like the follow content**
![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/8872546/72c2fe20-3241-45a1-8628-d32aa9e6b713)

**Comment by mayurankv** [comment]
Thanks for the bug report! This is a parsing error in the inline code I've been meaning to fix! I'll try and get round to it soon sorry!

**Comment by mayurankv** [comment]
See #208 as well

**Comment by Tback1** [comment]
No apologies, thank you for your hard work. Best wishes

**Comment by mayurankv** [comment]
I believe this should now be fixed and will be included in the next release. Currently working on another feature and will release as soon as that is done!

**Comment by mayurankv** [comment]
Released now!
