### ISSUE TITLE
Feature Request: Frontmatter Syntax Highlight (YAML)

### ISSUE THREAD

**Issue by juanbretti** [mayurankv/Obsidian-Code-Styler#213]
## Summary
Frontmatter is a YAML code.
Now it is shown as plain text.
It would be great to add syntax highlight for data inside a frontmatter block

### Basic example

![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/10165911/ac2fc55a-c1ef-4ed2-834c-39bb137a3059)

### Motivation
For a better edit of the yaml

## Existing Requests?
This is related to https://github.com/deathau/cm-editor-syntax-highlight-obsidian/issues/10 and https://github.com/deathau/cm-editor-syntax-highlight-obsidian/issues/40, from the related project.

**Comment by juanbretti** [comment]
Haha! Great question. I like the inline frontmatter editor :)

Sometimes, I edit the frontmatter at the **source**, when I try to add a manual link or **edit** a tag... Not every _edit_ can be done at the new-properties editor.

**Comment by mayurankv** [comment]
Just to clarify, do you mean source mode in editing view? As opposed to live preview or turning off the properties editor? To be completely honest with you, I'm not 100% sure how I'd do this since in live preview, you generally need to use the tokens that obsidian already provides to style things. I could definitely look into it but I'm also not sure if this falls within the scope of this plugin? If you explain why you think it should be part of this plugin as opposed to a metadata plugin or some other plugin, I'm happy to look into it. Looking forward to hearing your thoughts.

**Comment by mayurankv** [comment]
I actually reckon I can do this pretty easily so I'm happy to give it a go.

**Comment by juanbretti** [comment]
@mayurankv thank you for considering this FR.

Yes, I edit the frontmatter-properties-YAML using the "Source mode" (`</>`).
The idea, is to be able to 
- fix typos in tags or links, 
- converting a list of strings into a list of *tags*, 
- pasting a search resultas a list of references for a note, 
- etc.

The thing is, as you can imagine, editing this YAML with color highlighting is nicer and better in terms of not making mistakes.
Does it make sense?

To clarify, I 99.9999% of the time use my editor using the "Live Preview" mode (🖊️).

**Comment by mayurankv** [comment]
Does this appear fine? 
<img width="213" alt="image" src="https://github.com/mayurankv/Obsidian-Code-Styler/assets/69591376/60d56914-bff4-4276-8175-07dfd508cac5">

The only thing I'm not sure about is the colour of the `---` lines. Do you think they should be a different colour or maybe just the colour of punctuation?

**Comment by mayurankv** [comment]
Either way this is completed and will be included in the next release. Look forward to hearing your thoughts.

**Comment by mayurankv** [comment]
Decided on this:

<img width="239" alt="image" src="https://github.com/mayurankv/Obsidian-Code-Styler/assets/69591376/56f02fa6-aac2-4461-ba5c-089b9febc9e0">

**Comment by juanbretti** [comment]
@mayurankv , wow! Looks great.
Both look great.

I think I go with the second option.

![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/10165911/df6cf268-539d-452d-864b-add2aad6d39f)

To be consistent with:

![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/10165911/591b72ca-9423-41b0-9d3c-0ae3d1f0b3a5)

I mean, the delimiter `---` and ` ``` ` are not colored.

**Comment by mayurankv** [comment]
Cool, I'll go with that then. Cheers.

**Comment by juanbretti** [comment]
**Thank you!** For maintaining this great Obsidian plugin... and hearing user's ideas.

**Comment by mayurankv** [comment]
Released now!

**Comment by juanbretti** [comment]
Works as intended! Thank you.

Could I ask something **more**...
Check this frontmatter:

![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/10165911/623f2dbd-fdeb-4fa1-8192-52b3f8f7f88c)

Allows you to write the minutes, but those are colored purple.
Same happened with the other related plugin (https://github.com/mayurankv/Obsidian-Code-Styler).

Looks like YAML does not like the `:`. Am I correct?
The only solution would be from my side to write the whole value between quotes, right?
More at https://stackoverflow.com/questions/11301650/how-to-escape-indicator-characters-colon-and-hyphen-in-yaml

Anyhow, **looks great! Thanks!** 
I have updated my Obsidian and it works great!

**Comment by mayurankv** [comment]
That is correct that you can't have a bare colon in a yaml value field. I could try and implement something to avoid that for dates in particular regarding highlighting but I have no control over how Obsidian reads the yaml. Does this get recognised as a proper date for you by Obsidian? If you got to reading mode, does your frontmatter show an error?

Overall I would honestly suggest looking for a way to get that time information in a YAML compliant way, it'll help you if you ever want to use something other than Obsidian and it's just better practice, but yeah let me know.

**Comment by juanbretti** [comment]
**Forget it.**
If you also agree this is the way YAML should work. Leave it as it is.

Strange is the implementation from Obsidian.
Take a look.

No issues mentioned by Obsidian. I mean, when I mouse-hover the pointer to the date element, it does not report any issue.
![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/10165911/2341bc76-51d7-4232-a37c-150c3dabc524)

This is the `source mode` content:
![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/10165911/9e6b7537-cd81-469a-a6b7-3f31b3d77e5c)

And this date was added using the date-picker:
![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/10165911/79a0017d-19a3-47e3-8af8-5f3db84119eb)

Again, as it is now. It is perfect. **Thank you**!
