### ISSUE TITLE
Feature Request: Language Icon for "Query"

### ISSUE THREAD

**Issue by juanbretti** [mayurankv/Obsidian-Code-Styler#220]
## Summary
It would be nice to have a language icon for the "Query" code objects.
I mean for this: https://help.obsidian.md/Plugins/Search#Embed+search+results+in+a+note

No icon is shown:

![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/10165911/ce8b1f6f-b560-4699-8429-6e91a1d2542a)

The code I am using is:
````
```query
tag:#tesorería
```
````

### Basic example
Have an icon like, this case of `javascript`.

![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/10165911/017db330-4564-47ae-a3ff-d4f1de6a47f9)

### Motivation
Consistency with other code blocks.
To highlight a block type.
Nicer :)

## Existing Requests?
Haven't found any related requests.

This FR could be a dilemma because the query loupe icon ...
![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/10165911/5fac2eaa-fb16-4083-83c2-115042acaf5e)
... is already being shown.
Open to discussion and suggestions.

**Comment by mayurankv** [comment]
This makes sense! I'll add this to the todo file. I think removing the other icon should be fine.

**Comment by juanbretti** [comment]
Thinking out loud... If you make an "icon" for [Query](https://help.obsidian.md/Plugins/Search#Embed+search+results+in+a+note), maybe you should also make one for [DataView](https://blacksmithgu.github.io/obsidian-dataview/)?

**Comment by mayurankv** [comment]
Thing is I was actually going to come back to you and ask what icon I should use for query? I'm not actually sure haha. Similar for data view. If you can suggest sources, happy to use them.

**Comment by juanbretti** [comment]
I have been thinking about this FR, doing some icon research, and conclude it is better to leave "Query" and "Dataview" with no icon for now.
Because what to use, [binoculars](https://www.flaticon.com/search?word=binoculars) and a [loupe](https://www.flaticon.com/search?word=search)? Why? 
The original developers have not defined an icon, should I?

I am OK if you want to close this issue.
**Thank you!**

More [sources](https://dev.to/ananiket/revamp-your-icon-game-the-best-open-source-icon-libraries-of-2023-1edg) of icons.

**Comment by mayurankv** [comment]
Well I can do any svg icon but with dataview, I think it would be presumptuous for me to unilaterally add some icon, it should be up to the dev. Similarly, I think the way the query blocks render now is generally fine. I think I agree, I'll close this issue now but if there's a change like a new icon or something, please feel free to come back to this and I'll reopen it.
