### ISSUE TITLE
Bug: Every time the plugin is updated, my custom theme is forced to be deleted

### ISSUE THREAD

**Issue by liuke101** [mayurankv/Obsidian-Code-Styler#228]
Every time the plugin is updated, my custom theme is forced to be deleted

**Comment by mayurankv** [comment]
Really sorry about this. There was meant to be some logic which automatically updates themes to prevent this occurring but, I've been made aware of some issues with it working. I'm going to refer this to #227 as the original issue. I really hope to fix this for future releases!
