### ISSUE TITLE
Bug: Title doesn't render properly if added to existing codeblock

### ISSUE THREAD

**Issue by wakelin-g** [mayurankv/Obsidian-Code-Styler#236]
Thank you for the wonderful plugin which I've only found recently. 

## Describe the bug

There's a strange bug I've come across with regards to code block titles. If you have a pre-existing code block and you attempt to add a title to it, the title will render in editing but not reading mode.

For example, if you have a code block holding preexisting code and you add a title to the header, it will render in live preview, but will disappear if you then switch to reading mode. However, if you add the title _before_ adding any code to the block, it renders just fine in both modes.

### Steps to reproduce

Create a code block, populate it with code, and then add a title.

### Expected behaviour

Code block title renders in all modes when added to existing code block.

### Current behaviour

Code block title renders in live view/editing but not reading mode when added to existing code block.

### Environment

- Plugin Version: 1.1.7
- Obsidian Version: Version 1.5.8 (Installer 1.4.14)
- Platform:  Desktop
- OS: macOS Sonoma 14.3.1
- Theme: N/A
- CSS Snippets: N/A

### Screenshots

Adding title to pre-existing code blocK:

![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/86983768/e63ccd2d-b255-49a8-8b8e-a16271cddc87)
![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/86983768/d0ac6e7e-022e-4b38-8d7b-1e5d6062ad70)

Adding title to new code block:

![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/86983768/d8c6a0b2-036c-4714-9a88-8ba6481c17f9)
![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/86983768/c40686ee-93ef-4e53-a469-4357a0e7e389)

**Comment by Experiment59** [comment]
Would like to add that this applies for re-titling a new code block as well.

If you title a new block before adding any code to it, the title will successfully render in both live preview and reading mode. However, once you change the title, it will only update in live preview mode, and reading mode will continue to display the previous title.

**Comment by mayurankv** [comment]
This is unfortunately an upstream bug for obsidian based on setting the codeblock parameters after the ` ``` ` syntax. The obsidian markdown updater doesn't parse anything after the backticks so changing the title doesn't trigger a change in markdown from Obsidian's perspective and Reading mode then won't change anything from how it was before despite the codeblock title changing. I have tried to circumvent this issue but there literally isn't a trigger that recognises that you've made the change after the backticks so no method to force a reading view refresh. See issue #16. If anyone does manage to come up with a possible method, I'd love to see it. Sorry I can't fully resolve this!

**Comment by yaoyhu** [comment]
There is a workaround for now, assume you have code like this:
```python
```

**Comment by yaoyhu** [comment]
There is a workaround for now:
- delete the language keyword after `` ``` `` and enter reading mode. 
- Then add the language title with whatever title, and render it again in reading mode.
