### ISSUE TITLE
Bug: header wider than text margin in live preview...

### ISSUE THREAD

**Issue by olearydj** [mayurankv/Obsidian-Code-Styler#53]
## Describe the bug

When using the Minimal theme, in live preview mode, your (awesome) plugin renders the header is wider than the text.

### Steps to reproduce

With the minimal theme installed and active, switch between reader and live preview. Note the header width.

````markdown
not relevant - behavior doesn't depend on code / language
````

### Expected behaviour

Width of header should be consistent.

### Current behaviour

It is not.

### Environment

- Plugin Version: 1.01
- Obsidian Version:  1.4.2, installer 1.3.5
- Platform:  desktop
- OS:  macos

minimal 7.1.1

### Screenshots

<img width="878" alt="image" src="https://github.com/mayurankv/Obsidian-Code-Styler/assets/42705243/3b9a2d38-e814-4b1e-9227-07ab1c5e2511">

### Additional context

No console errors. I can provide my minimal settings if you need them.
Great start to this. Lovely!

**Comment by mayurankv** [comment]
Thanks for the report, I thought I'd implemented a fix for this but it clearly isn't working. I'll try to reproduce this and let you know if I need anything else!

**Comment by mayurankv** [comment]
I believe this is fixed with version /../../releases/tag/1.0.0. Please let me know if you still have any issues!

**Comment by olearydj** [comment]
It does seem fixed! Thanks. This plugin is so great out of the box. I will add a couple more bug reports (performance?, inline code ignores on/off toggle) and a request (style yaml) over the weekend.

**Comment by mayurankv** [comment]
Hey, no rush but I'd love to hear the other bug reports you have! (Though hopefully the inline code toggle should be respected with the latest update!)

**Comment by mayurankv** [comment]
Currently refactoring the code so if you do have any outstanding issues, hopefully that should solve them!
