### ISSUE TITLE
Bug: Code blocks don't expand correctly

### ISSUE THREAD

**Issue by Ce1este** [mayurankv/Obsidian-Code-Styler#59]
In read mode, code blocks don't expand properly in some instances

## Describe the bug
Maybe CSS bug

### Steps to reproduce

This is the code I used in the screenshot.

````markdown
-   lowercase

```diff title:diff hl:1
- Hello, I am using Obsidian.
+ hello, i am using obsidian.
```

-   capitalize word

```diff
- Hello, I am using Obsidian.
+ Hello, I Am Using Obsidian.
```

-   capitalize sentence

```diff
- hello, I am using Obsidian.
+ Hello, I am using Obsidian.
^
```

-   title case

```diff
- Obsidian is a good app.
+ Obsidian Is a Good App.
		  ^
```

-   redundant spaces

```diff
- There  are so   many redundant      blanks
+ There are so many redundant blanks
```

-   merge broken paragraph

```diff
- This paragraph is broken 
- into several lines. I want 
- those lines merged!
- 
- And this is second paragraph. There is a blank line between 
- two paragraph, indicating that they should not be merged into 
- one paragraph!

+ This paragraph is broken into several lines. I want those lines merged!
+
+ And this is second paragraph. There is a blank line between two paragraph, indicating that they should not be merged into one paragraph!
```

-   bullet list

```diff
- • first, blahblah • second, blahblah • third, blahblah

+ - first, blahblah 
+ - second, blahblah 
+ - third, blahblah
```

-   ordered list

```diff
- a) first, blahblah b) second, blahblah c) third, blahblah
- i) first, blahblah ii) second, blahblah iii) third, blahblah

+ 1. first, blahblah 
+ 2. second, blahblah 
+ 3. third, blahblah
```
````

### Expected behaviour
The code blocks expand correctly in read mode.

### Current behaviour
Rendering a single code block doesn't run into this problem, but **long articles**(Screenshot-3) or have **more code blocks**(Screenshots-1) may run into this problem.
If I use 'ignore' setting, the code block will expand normally. (Screenshot-2)
This problem behaves exactly the same in Windows11 and iPadOS.

### Environment
- Plugin Version: 1.0.2
- Obsidian Version:  v1.3.7
- Platform: Desktop and Mobile
- OS:  Windows11 and iPadOS
- Obsidian theme: AnuPpuccin

### Screenshots
![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/51806751/823a411d-c304-407a-ae67-fc41645a48b2)

![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/51806751/cacdcea9-37d7-4c00-88a3-a7518c8e6935)

![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/51806751/0b98a4a8-36c7-4491-9505-9a3b86978626)

### Additional context
no console error

(I've noticed that the code block has an unfolding animation when the page is opened, and I wonder if the problem is related to not triggering this correctly.)

Finally thanks for making the plugin, it's the most aesthetically pleasing code block style plugin I've ever used.

**Comment by Ce1este** [comment]
Unfortunately, I updated to version 1.3, but this problem still exists on my computer.

I've tried turning off all the css code snippets I'm using, but I'm still getting this problem.

**Comment by Ce1este** [comment]
To make some additions：
If I make some changes in the code block which is not expanding properly, then this time when I go into reading mode this block of code will display properly.
But closing this page and reopening it will not work again.

**Comment by mayurankv** [comment]
Ok this is an issue related to using `max-height` for folding animations. I'm currently trying to think of an alternative to this asap. I'll update this thread when I implement that change.

**Comment by mayurankv** [comment]
This should now be eliminated with the removal of `max-height` outside of animations in release 1.0.4. Please comment if this doesn't actually fix your issue but I'm going to close this now (I'm pretty sure the fix should eliminate this).
