### ISSUE TITLE
Bug: About `Wrap Lines on Click` and `header title`

### ISSUE THREAD

**Issue by magicdmer** [mayurankv/Obsidian-Code-Styler#66]
## Describe the bug
1. After update to 1.0.4, `Wrap Lines on Click` not work , replace 1.0.3 main.js works well
2. `cpp title:hello` or `fold title:hello`， when i change the title text, must reopen note file to let it takes affect

### Environment
- Plugin Version: 1.0.4
- Obsidian Version:  1.3.7
- Platform:  Desktop
- OS:  Windows 11
- Theme:  blue topaz

**Comment by mayurankv** [comment]
Thanks for the report! I'm aware of the wrap issue (literally a silly oversight - this is ready to be released in the next version very soon).

**Comment by mayurankv** [comment]
For point 2, is that only in reading mode? Or in editing mode as well? If reading mode only, unfortunately this is an upstream problem with Obsidian, see #16.

**Comment by mayurankv** [comment]
Please try update to version [1.0.5](../releases/tag/1.0.5), point 1 should be fixed now.
Having tested point 2, I'm pretty sure it works as expected in editing mode so I presume your issue is linked to the related issue. If I'm wrong please open a new bug report!

**Comment by magicdmer** [comment]
> Please try update to version [1.0.5](../releases/tag/1.0.5), point 1 should be fixed now. Having tested point 2, I'm pretty sure it works as expected in editing mode so I presume your issue is linked to the related issue. If I'm wrong please open a new bug report!

Saddly, point 1 not be fixed ,  point 2 have tested on read mode, you are right
