### ISSUE TITLE
Bug: not install success

### ISSUE THREAD

**Issue by ccfuncy** [mayurankv/Obsidian-Code-Styler#70]
## Describe the bug

![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/35862080/7493bc81-27c7-4e51-8440-919578b92da9)

### Steps to reproduce

I tried to install code-style from Obsidian's third-party marketplace, but it failed with no error messages.

### Expected behaviour

install success
### Current behaviour

install faild
### Environment

- Plugin Version: 1.0.5
- Obsidian Version: 1.3.7
- Platform:  Desktop
- OS:  Windows11
- Theme:  default
- CSS Snippets:  not

**Comment by mayurankv** [comment]
Wow, that's unexpected. Can you try again with the latest release? If that fails, can you copy the output of the log?

**Comment by JensDienst** [comment]
It works now (again), there was an missmatch betwenn your Versions in Git and Obsidian. :)

**Comment by mayurankv** [comment]
Ah, I was having some confusion about how best to update versions consistently so probably messed something up. Good to know! Cheers!

**Comment by ccfuncy** [comment]
thanks, I had addressed this solution through manually install, its works
