### ISSUE TITLE
Bug: unwrap not working

### ISSUE THREAD

**Issue by GladioFeng** [mayurankv/Obsidian-Code-Styler#71]
## Describe the bug
**Unwrap not working in edit mode and preview mode**

### Steps to reproduce

````markdown

````

### Environment

- Plugin Version: 
- Obsidian Version:  
- Platform:  
- OS:   **Mac Os**
- Theme:   **AnuPpuccin**
- CSS Snippets:  

### Screenshots

![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/100987925/064f0083-da19-4bed-9af3-67edbf3f2635)
![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/100987925/3dc56af8-8496-4553-b832-c30ac222cfb3)

**Comment by mayurankv** [comment]
Please try update to version [1.0.5](../releases/tag/1.0.5), it should be fixed now.

**Comment by GladioFeng** [comment]
Thanks 🤗
