### ISSUE TITLE
Feature Request: Horizontal scroll bar visulization

### ISSUE THREAD

**Issue by GladioFeng** [mayurankv/Obsidian-Code-Styler#79]
## Summary

**Show the Horizontal scroll bar like vscode or other markdown editor**. It is a convenience function for everyone, i think. 🤔
Thanks!
### Basic example

<img width="1424" alt="image" src="https://github.com/mayurankv/Obsidian-Code-Styler/assets/100987925/a251005c-5c07-44a6-ae99-777f220b4242">

**Comment by mayurankv** [comment]
Sorry for the slow response. Looking into this.

**Comment by mayurankv** [comment]
Ok this will be fixed in the next release!
