### ISSUE TITLE
Bug: Template Literals not render in reading more

### ISSUE THREAD

**Issue by uzza1hossain** [mayurankv/Obsidian-Code-Styler#80]
````js
let x;
const name = 'John';
const age = 30;
 
x = 'Hello, my name is ' + name + ' and I am ' + age + ' years old.'

// Template Literals/string
x = `Hello my name is ${name} and I am ${age} years old.`

console.log(x);

````

### Expected behaviour

Everything should render normally in reading more.

### Current behaviour

`Hello my name is ${name} and I am ${age} years old.` not render in reading mode.

**Comment by mayurankv** [comment]
Hey! Thanks for the bug report. This is a parsing problem (I've been parsing HTML with a non-ideal parser). I'll tyr get this fixed and released very soon!

**Comment by mayurankv** [comment]
Related to #28. Should be fixed with upcoming release.
