### ISSUE TITLE
Bug: Flickering when modifying files with dataview code blocks in live preview

### ISSUE THREAD

**Issue by SandWoodJones** [mayurankv/Obsidian-Code-Styler#81]
## Describe the bug

I use a dataview snippet in all my notes (through templates) and after installing this plugin I've noticed my screen flickering after a few seconds of me changing something in a note. This only happens in live preview mode.

### Steps to reproduce

Add
``` dataviewjs
dv.span("**Created on: **") + dv.span(dv.date(dv.current().file.cday)) + dv.span("**\nLast modified on: **") + dv.span(dv.date(dv.current().file.mtime))
```
To the top of a new note and edit it.

### Environment

- Plugin Version: 1.0.5 
- Obsidian Version: 1.3.7  
- Platform: Desktop 
- OS: Windows 
- Theme: Atom 
- CSS Snippets: Yes but the problem still happens with them disabled. 

### Screenshots

![Obsidian_xCm2hWNjpb](https://github.com/mayurankv/Obsidian-Code-Styler/assets/35671374/69b2460c-7f93-4764-a2de-aae980fbc4ae)

**Comment by SandWoodJones** [comment]
Do you mean the "Ignore Codeblocks" setting? In t hat case its the default: `dataview, dataviewjs, math`

**Comment by mayurankv** [comment]
Hey I've managed to replicate this. I have an idea of what's needed to eliminate this issue. Shouldn't be too long to release!

**Comment by mayurankv** [comment]
This should be fixed in the next release.
