### ISSUE TITLE
Feature Request: toggle to disable inline code styling

### ISSUE THREAD

**Issue by olearydj** [mayurankv/Obsidian-Code-Styler#90]
I would prefer to use the inline code styling (font, size, color, etc.) from Minimal but there is no way to disable this in OCS. If possible I would like to be able to keep syntax highlighting active without the base styling. Perhaps a button to copy theme settings to OCS styling settings would be best.

## Summary

see above

### Basic example

n/a

### Motivation

minimize duplication of style settings while benefitting from OCS feature set

## Existing Requests?

I did not see one.

**Comment by mayurankv** [comment]
Ooh, that's a very good point! I'll try and work that in when possible. Apologies but I've got a few higher priority things to work through but its definitely something I'm going to add. (Need to do a bit of a settings revamp to be honest, its a bit cluttered).

**Comment by mayurankv** [comment]
Unfortunately, to do this, I'd like to implement #107 first. That is going to be pretty high priority so shouldn't take too long. I'll hopefully get to this soon!

**Comment by mayurankv** [comment]
This is now done and will be released in the next release.
