### ISSUE TITLE
Bug: Nested Codeblocks

### ISSUE THREAD

**Issue by Aetherinox** [mayurankv/Obsidian-Code-Styler#92]
## Describe the bug

When attempting to nest codeblocks, editing mode displays the codeblock correctly. However, Live mode displays a blank codeblock.

### Steps to reproduce

In the example below, I keep examples for the dataview plugin in a document. The outer codeblock formats as markdown using an extra tick. Then the inner code is the actual dataview code.

`````markdown
````markdown
```dataview
table list(file.ctime.day,file.ctime.month) as creation
```
````
`````

### Expected behaviour

Nested codeblocks should appear the same in Edit and Live modes.

### Current behaviour

**Edit Mode** works properly and displays the nested codeblocks
**Live Mode** displays a blank codeblock

### Environment

- Plugin Version: **v1.0.7**
- Obsidian Version:  **v1.3.7**
- Platform:  **Desktop**
- OS:  **Windows 11 Pro**
- Theme:  **Blue Topaz**
- CSS Snippets:  **No**

### Screenshots

**Edit Mode**
![obsid_edit](https://github.com/mayurankv/Obsidian-Code-Styler/assets/118329232/c5623c14-edd6-4165-9922-373bf491b331)

**Live Mode**
![obsid_live](https://github.com/mayurankv/Obsidian-Code-Styler/assets/118329232/c8bef7fa-9491-41c5-adf4-6be7a68d0ad1)

### Additional context

Once this plugin is disabled, nested codeblocks function properly in edit and live modes.

**Comment by mayurankv** [comment]
Thanks for the bug report, will look into it.

**Comment by mayurankv** [comment]
Hey I can't reproduce this unfortunately. I actually need to fix a non-trivial problem before the next release so I don't know whether something small I've changed between releases could have fixed this but I doubt it. Does this issue still occur in a new vault?

**Comment by Aetherinox** [comment]
Thought I replied to this.

In regards to any plugins causing potential issues. I tried all of this out on a stock install of Obsidian. Default theme, absolutely zero plugins installed, and the issue still happens.

As soon as I scroll down to the bottom of a code block, the text starts shoving itself to the right. 

I've tried to trigger it every-which-way I can. The issue doesn't happen if you do a regular code block with no language defined. As soon as I add `bash` to the code block, it starts shifting.

I was trying to see if a particular character was making it worse or not, but that doesn't seem to be the case, sometimes it acts like it's all based on how many characters are in the block all-together. But sometimes it triggers with more or less.

At this point, it's completely random, and I can't find the actual root cause.

**Comment by mayurankv** [comment]
Yep that will definitely be my number 1 priority.

**Comment by Aetherinox** [comment]
Thanks. I would be the happiest person in the world. I use Obsidian and your plugin religiously, and I have a lot of codeblocks from all my development work.

Right now as soon as I scroll down in a code block, all the text runs of the screen. Feel like I'm playing pacman and seeing if I can hurry up and copy the code before it runs away. Then I have to leave the doc and come back to get it fixed lol

**Comment by mayurankv** [comment]
For clarity I'm pretty sure this is related to #17 about how to calculate the gutter width for line numbers in editing mode and pertains to lines 56-63 and 311 in `EditingView.ts`.

If you have any suggestions on an alternative way to calculate this, that would be very welcome but I'll definitely have a think about how I can switch this out!

Appreciate the kind words!

**Comment by Aetherinox** [comment]
Just trying to clean up your workload.

Not sure if it was accidentally fixed in your last update since I first reported this, but nested codeblocks are working fine. I tried creating blocks with titles, highlights, etc.

From what I'm seeing, they all work properly.

![pzdbQJm](https://github.com/mayurankv/Obsidian-Code-Styler/assets/118329232/95f22e30-d66e-4940-978f-892153006f05)
