### ISSUE TITLE
Feature Request: improved support for Execute Code plugin

### ISSUE THREAD

**Issue by Mideks** [mayurankv/Obsidian-Code-Styler#96]
Hi, since you indicated that the plugin supports compatibility with the Execute Code plugin (and does it incredibly well!), I would like to suggest 2 improvements related to this: 

1. Blocks that start with run-[lang], e.g. `run-python` are not treated as blocks of the corresponding language, thus losing syntax highlighting, language icon, and all other improvements that your plugin adds. Below is an example with two blocks: `run-python` and `python` 
![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/38502324/7464e6dc-2b5e-4bcb-a6b8-72b8328dfe37) 

2. In the ExecuteCode plugin there is a parameter that is responsible for assigning a label to a block so that it can be referenced from other blocks (imported). This is very similar to the file name (title) you have in your plugin. I think it would be convenient if your plugin would recognize these labels and use them as title, because now in this case you have to write like this: 
![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/38502324/bb851166-76b2-4b81-9e6a-cdcf0f5220d7) 
And I think it would be good to add a setting for this (in case not everyone needs it), and maybe make explicit specification of title more priority.

**Comment by mayurankv** [comment]
Hey thanks for the request.

For point 1, unfortunately, I'm still waiting on #27 for live preview support for `run-*` codeblocks.
In reading mode though, I could do some processing of the codeblock language - i.e. looking to see if it is `run-*` and then actually converting it to `*`. However, this could lead to false positives if a user wants to define a non-execute code plugin language such as `run-code`. Do you think it would be a suitable approach to check if the execute code plugin is enabled and if so do that processing?

For point 2, I can definitely try and add this as an option. In terms of adding a setting, where would you expect this setting to go? Do you think a new settings section for plugin compatability is needed?

**Comment by mayurankv** [comment]
#98 will take forward point 2 (I thought it might be easier to split the FR and also include the extra parameters).

**Comment by mayurankv** [comment]
Going to take a look into how the execute code plugin itself deals with `run-*` codeblocks to replicate when i would apply the logic described above.

**Comment by mayurankv** [comment]
I will close this when I've dealt with the `run-*` codeblocks in reading mode.

**Comment by mayurankv** [comment]
This should be released in the next release. The plugin will only do this to codeblocks that are modified by the execute code plugin.
